#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_mfad           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss --save_hilora_clip --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v100/rgbtvg_mfad/best_checkpoint.pth --eval_set test    --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v100/rgbtvg_mfad;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_mfad           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 1 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v101/rgbtvg_mfad/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v101/rgbtvg_mfad;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_mfad           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 2 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v102/rgbtvg_mfad/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v102/rgbtvg_mfad;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_mfad           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 3 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v103/rgbtvg_mfad/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v103/rgbtvg_mfad;
#
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_mfad           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss --save_hilora_clip --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_mfad/best_checkpoint.pth --eval_set test    --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_mfad;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_mfad           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 1 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v101/rgbtvg_mfad/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v101/rgbtvg_mfad;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_mfad           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 2 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v102/rgbtvg_mfad/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v102/rgbtvg_mfad;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_mfad           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 3 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v103/rgbtvg_mfad/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v103/rgbtvg_mfad;
#
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_m3fd           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss --save_hilora_clip --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_m3fd/best_checkpoint.pth --eval_set test    --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_m3fd;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_m3fd           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 1 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v101/rgbtvg_m3fd/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v101/rgbtvg_m3fd;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_m3fd           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 2 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v102/rgbtvg_m3fd/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v102/rgbtvg_m3fd;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_m3fd           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 3 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v103/rgbtvg_m3fd/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v103/rgbtvg_m3fd;
#
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_m3fd           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss --save_hilora_clip --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v100/rgbtvg_m3fd/best_checkpoint.pth --eval_set test    --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v100/rgbtvg_m3fd;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_m3fd           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 1 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v101/rgbtvg_m3fd/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v101/rgbtvg_m3fd;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_m3fd           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 2 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v102/rgbtvg_m3fd/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v102/rgbtvg_m3fd;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_m3fd           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 3 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v103/rgbtvg_m3fd/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v103/rgbtvg_m3fd;
#
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss --save_hilora_clip --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_flir/best_checkpoint.pth --eval_set test    --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_flir;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 1 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v101/rgbtvg_flir/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v101/rgbtvg_flir;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 2 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v102/rgbtvg_flir/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v102/rgbtvg_flir;
#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 3 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v103/rgbtvg_flir/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v103/rgbtvg_flir;

CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss --save_hilora_clip --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v100/rgbtvg_flir/best_checkpoint.pth --eval_set test    --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v100/rgbtvg_flir;
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 1 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v101/rgbtvg_flir/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v101/rgbtvg_flir;
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 2 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v102/rgbtvg_flir/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v102/rgbtvg_flir;
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env hivg_eval.py --num_workers 2 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 3 --data_root /home/shared/datasets/VG/image_data --split_root /home/shared/datasets/VG/ref_data_shuffled --eval_model /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_hivg_weight/output_v103/rgbtvg_flir/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v103/rgbtvg_flir;


CUDA_VISIBLE_DEVICES=0 python hivg_train.py --num_workers 0 --modality rgbt --epochs 200  --batch_size 4 --lr 0.00025   --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 640 --max_query_len 77 --normalize_before --enable_adaptive_weights --dataset rgbtvg_flir      --use_contrastive_loss  --use_rtcc_constrain_loss --use_mask_loss                                       --data_root /home/shared/datasets/VG/image_data  --split_root /home/shared/datasets/VG/ref_data_shuffled  --clip_model /home/shared/pretrain_model/pretrained_weights/CLIP/clip_b_ml_cascade_maskrcnn_model_224.pth --output_dir /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_flir --sup_type full;
CUDA_VISIBLE_DEVICES=0 python hivg_train.py --num_workers 0 --modality rgbt --epochs 200  --batch_size 4 --lr 0.00025   --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 640 --max_query_len 77 --normalize_before --enable_adaptive_weights --dataset rgbtvg_m3fd      --use_contrastive_loss  --use_rtcc_constrain_loss --use_mask_loss                                       --data_root /home/shared/datasets/VG/image_data  --split_root /home/shared/datasets/VG/ref_data_shuffled  --clip_model /home/shared/pretrain_model/pretrained_weights/CLIP/clip_b_ml_cascade_maskrcnn_model_224.pth --output_dir /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_flir --sup_type full;
CUDA_VISIBLE_DEVICES=0 python hivg_train.py --num_workers 0 --modality rgbt --epochs 200  --batch_size 4 --lr 0.00025   --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 640 --max_query_len 77 --normalize_before --enable_adaptive_weights --dataset rgbtvg_mfad      --use_contrastive_loss  --use_rtcc_constrain_loss --use_mask_loss                                       --data_root /home/shared/datasets/VG/image_data  --split_root /home/shared/datasets/VG/ref_data_shuffled  --clip_model /home/shared/pretrain_model/pretrained_weights/CLIP/clip_b_ml_cascade_maskrcnn_model_224.pth --output_dir /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_flir --sup_type full;
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env  hivg_train.py --num_workers 4 --modality rgbt --epochs 200  --batch_size 4 --lr 0.00025   --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 640 --max_query_len 77 --normalize_before --enable_adaptive_weights --dataset rgbtvg_mixup      --use_contrastive_loss  --use_rtcc_constrain_loss --use_mask_loss                                       --data_root /home/shared/datasets/VG/image_data  --split_root /home/shared/datasets/VG/ref_data_shuffled  --clip_model /home/shared/pretrain_model/pretrained_weights/CLIP/clip_b_ml_cascade_maskrcnn_model_224.pth --output_dir /home/xjw/RGBTVG-benchmark/output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_flir --sup_type full;

CUDA_VISIBLE_DEVICES=0 python hivg_train.py --num_workers 0 --modality rgbt --epochs 200  --batch_size 4 --lr 0.00025   --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 640 --max_query_len 77 --normalize_before --enable_adaptive_weights --dataset rgbtvg_flir      --use_contrastive_loss  --use_rtcc_constrain_loss --use_mask_loss                                        --data_root ../dataset_and_pretrain_model/datasets/VG/image_data  --split_root ../dataset_and_pretrain_model/datasets/VG/ref_data_shuffled  --clip_model ../dataset_and_pretrain_model/pretrain_model/pretrained_weights/CLIP/clip_b_ml_cascade_maskrcnn_model_224.pth  --output_dir ./output_training/rgbt_finetuning_base_clip_weight/output_v100/rgbtvg_flir --sup_type full;


CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 28888 --use_env hivg_eval.py --num_workers 0 --batch_size 16  --dataset rgbtvg_flir           --vl_hidden_dim 512 --imsize 640 --max_query_len 77 --normalize_before --enable_adaptive_weights --use_mask_loss  --save_hilora_clip --hi_lora_stage 3 --data_root ../dataset_and_pretrain_model/datasets/VG/image_data --split_root ../dataset_and_pretrain_model/datasets/VG/ref_data_shuffled --eval_model ../dataset_and_pretrain_model/pretrain_model/pretrained_weights/HiVG/mixup_pretraining_base/mixup/best_checkpoint.pth      --eval_set test  --output_dir ./output_training/rgbt_finetuning_base_hivg_weight/output_v103/rgbtvg_flir;

##clipvg
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env train_clip_vg.py --num_workers 0 --modality rgbt --epochs 200 --batch_size 4 --lr 0.00025  --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 640 --max_query_len 77   --dataset rgbtvg_m3fd     --data_root /home/shared/datasets/VG/image_data  --split_root /home/shared/datasets/VG/ref_data_shuffled --output_dir ./output_training/rgbtvg_mixup --sup_type full;
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --master_port 28888 --use_env train_clip_vg.py --num_workers 0 --modality rgbt --epochs 200 --batch_size 4 --lr 0.00025  --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 640 --max_query_len 77   --dataset rgbtvg_mixup      --data_root /home/shared/datasets/VG/image_data  --split_root /home/shared/datasets/VG/ref_data_shuffled --output_dir ./output_training/rgbtvg_mixup --sup_type full;



CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 28888 --use_env eval_clip_vg.py --modality rgbt --num_workers 0 --batch_size 64  --dataset rgbt_flir      --imsize 224 --max_query_len 77 --data_root ../dataset_and_pretrain_model/datasets/VG/image_data  --split_root ../dataset_and_pretrain_model/datasets/VG/ref_data_shuffled --eval_model ../output_training/CLIP_VG/rgbtvg_flir/best_checkpoint.pth      --eval_set val   --output_dir ./output_training/debug;


CUDA_VISIBLE_DEVICES=0 python hivg_train.py --num_workers 0 --modality rgbt --epochs 200  --batch_size 4 --lr 0.00025   --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 640 --max_query_len 77 --normalize_before --enable_adaptive_weights --dataset rgbtvg_flir      --use_contrastive_loss  --use_rtcc_constrain_loss --use_mask_loss                                       --data_root /home/shared/datasets/VG/image_data  --split_root /home/shared/datasets/VG/ref_data_shuffled  --clip_model /home/shared/pretrain_model/pretrained_weights/CLIP/clip_b_ml_cascade_maskrcnn_model_224.pth  --output_dir ./debug --sup_type full;
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 28888 --use_env  hivg_eval.py  --num_workers 4 --modality rgb --batch_size 64  --dataset unc           --imsize 224 --max_query_len 77 --normalize_before --use_mask_loss  --hi_lora_stage 3 --save_hilora_clip --mixup_pretrain --data_root "../dataset_and_pretrain_model/datasets/VG/image_data"   --split_root "../dataset_and_pretrain_model/datasets/VG/ref_data_shuffled"   --eval_model ../dataset_and_pretrain_model/pretrain_model/pretrained_weights/HiVG/mixup_pretraining_base/mixup/best_checkpoint.pth --eval_set val    --output_dir ./debug;
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 28888 --use_env hivg_eval.py  --num_workers 4 --modality rgb --batch_size 64  --dataset rgbtvg_flir --imsize 224 --max_query_len 77 --normalize_before --use_mask_loss  --hi_lora_stage 3 --save_hilora_clip --mixup_pretrain --data_root "../dataset_and_pretrain_model/datasets/VG/image_data"   --split_root "../dataset_and_pretrain_model/datasets/VG/ref_data_shuffled"   --eval_model ../dataset_and_pretrain_model/pretrain_model/pretrained_weights/HiVG/mixup_pretraining_base/mixup/best_checkpoint.pth --eval_set val    --output_dir ./debug;

 
#MMVG DEBUG script
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=1 --master_port 28887 mmvg_train.py --modality rgbt --num_workers 0 --epochs 60  --batch_size 32 --lr 0.00025   --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before  --mixup_pretrain --dataset rgbtvg_flir      --use_contrastive_loss  --use_rtcc_constrain_loss --use_mask_loss --data_root ../dataset_and_pretrain_model/datasets/VG/image_data  --split_root ../dataset_and_pretrain_model/datasets/VG/ref_data_shuffled   --clip_model ../dataset_and_pretrain_model/pretrain_model/pretrained_weights/CLIP/clip_b_ml_cascade_maskrcnn_model_224.pth  --output_dir ./debug --sup_type full  --retrain ../dataset_and_pretrain_model/pretrain_model/pretrained_weights/HiVG/mixup_pretraining_base/mixup/fixed_best_checkpoint.pth;
python mmvg_train.py --modality rgbt --num_workers 0 --epochs 60  --batch_size 16 --lr 0.00025   --lr_scheduler cosine --aug_crop --aug_scale --aug_translate  --vl_hidden_dim 512 --imsize 224 --max_query_len 77 --normalize_before  --mixup_pretrain --dataset rgbtvg_flir      --use_contrastive_loss  --use_rtcc_constrain_loss --use_mask_loss --data_root ../dataset_and_pretrain_model/datasets/VG/image_data  --split_root ../dataset_and_pretrain_model/datasets/VG/ref_data_shuffled   --clip_model ../dataset_and_pretrain_model/pretrain_model/pretrained_weights/CLIP/clip_b_ml_cascade_maskrcnn_model_224.pth  --output_dir ./debug --sup_type full  --retrain ../dataset_and_pretrain_model/pretrain_model/pretrained_weights/HiVG/mixup_pretraining_base/mixup/fixed_best_checkpoint.pth;
